### ISSUE TITLE
Support EconomyAPI-PM5

### ISSUE THREAD

**Issue by iTzAndrew33212** [supercrafter333/theRankShop#19]
Hi there

Just curious of youd be able to update this plugin so it would support the EconomyAPI-PM5 by mathchat900, bedrockeconomy is having a few issues of its own atm

**Comment by supercrafter333** [comment]
Support for EconomyAPI was removed for theRankShop-PM5 because EconomyAPI is no longer under (official) development since PM4 and it's not performant. You can add support for EconomyAPI-PM5 by creating a addon for theRankShop.

If you want to create a addon-plugin:
- Take a look at [`EconomyPluginMgr.php`](https://github.com/supercrafter333/theRankShop/blob/master/src/supercrafter333/theRankShop/Manager/Economy/EconomyPluginMgr.php)
- Use the [`EconomyPlugin`](https://github.com/supercrafter333/theRankShop/blob/master/src/supercrafter333/theRankShop/Manager/Economy/EconomyPlugin.php)-interface

theRankShop won't add support for EconomyAPI again.
