### ISSUE TITLE
Crash when buy a rank

### ISSUE THREAD

**Issue by TheAryqn** [supercrafter333/theRankShop#20]
When I buy a rank, my server crashes.

**Comment by supercrafter333** [comment]
Please send the crashdump. I can't help you without the crashdump.

**Comment by Aryanxxpro1234** [comment]
> Please send the crashdump. I can't help you without the crashdump.

PocketMine-MP Crash Dump Sat Mar 9 10:52:45 UTC 2024

PocketMine-MP version: 5.11.1+dev [Protocol 649]
Git commit: 1ca275e84ac3e01cf581cdd4d11c52b9e9adfe73-dirty
PHP version: 8.1.23
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedrockEconomy

Thread: Main
Error: BedrockEconomy requires xbox authentication.
File: plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/EventListener
Line: 175
Type: RuntimeException
Backtrace:
#0 pmsrc/src/event/RegisteredListener(61): cooldogedev\BedrockEconomy\EventListener->onPlayerCreation(object pocketmine\event\player\PlayerCreationEvent#175946)
#1 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerCreationEvent#175946)
#2 pmsrc/src/Server(574): pocketmine\event\Event->call()
#3 pmsrc/src/network/mcpe/NetworkSession(246): pocketmine\Server->createPlayer(object pocketmine\network\mcpe\NetworkSession#176721, object pocketmine\player\PlayerInfo#175987, false, object pocketmine\nbt\tag\CompoundTag#197997)
#4 pmsrc/src/network/mcpe/NetworkSession(918): pocketmine\network\mcpe\NetworkSession->createPlayer()
#5 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(146): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#6 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#175919)
#7 pmsrc/src/network/mcpe/NetworkSession(523): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#197969)
#8 pmsrc/src/network/mcpe/NetworkSession(461): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#175919, string[4] ....)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[8] .c.`a`..)
#10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[17] ....]..6J.B=8!.y.)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#198218)
#12 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#14 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#16 pmsrc/src/Server(1739): pocketmine\snooze\SleeperHandler->sleepUntil(float 1709981565.7305)
#17 pmsrc/src/Server(1105): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#4, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
#19 pmsrc/src/PocketMine(364): pocketmine\server()
#20 pmsrc(11): require(string[60] phar:///home/container/pocketmine-MP.phar/src/PocketMine.php)

**Comment by TheAryqn** [comment]
> Please send the crashdump. I can't help you without the crashdump.

PocketMine-MP Crash Dump Sat Mar 9 10:55:45 UTC 2024

PocketMine-MP version: 5.11.1+dev [Protocol 649]
Git commit: 1ca275e84ac3e01cf581cdd4d11c52b9e9adfe73-dirty
PHP version: 8.1.23
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: theRankShop

Thread: Main
Error: Cannot assign cooldogedev\BedrockEconomy\api\type\LegacyAPI to property supercrafter333\theRankShop\Manager\Economy\BedrockEconomyMgr::$bedrockEconomy of type cooldogedev\BedrockEconomy\api\BedrockEconomyAPI
File: plugins/theRankShop-1.phar/src/supercrafter333/theRankShop/Manager/Economy/BedrockEconomyMgr
Line: 18
Type: TypeError
Backtrace:
#0 plugins/theRankShop-1.phar/src/supercrafter333/theRankShop/Manager/Economy/EconomyPluginMgr(31): supercrafter333\theRankShop\Manager\Economy\BedrockEconomyMgr->__construct()
#1 plugins/theRankShop-1.phar/src/supercrafter333/theRankShop/Forms/theRankShopDefaultForms(111): supercrafter333\theRankShop\Manager\Economy\EconomyPluginMgr::getEconomyPlugin()
#2 plugins/theRankShop-1.phar/src/supercrafter333/theRankShop/libs/jojoe77777/FormAPI/Form(46): supercrafter333\theRankShop\Forms\theRankShopDefaultForms->supercrafter333\theRankShop\Forms\{closure}(object pocketmine\player\Player#174715, string[6] submit)
#3 pmsrc/src/player/Player(2141): supercrafter333\theRankShop\libs\jojoe77777\FormAPI\Form->handleResponse(object pocketmine\player\Player#174715, string[6] submit)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(981): pocketmine\player\Player->onFormSubmit(int 1, int 0)
#5 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#139316)
#6 pmsrc/src/network/mcpe/NetworkSession(523): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#78684)
#7 pmsrc/src/network/mcpe/NetworkSession(461): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#139316, string[7] e...0..)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[59] .cOedd2.b...........N1......;.T|....@.....LL...........h...)
#9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[68] ....Z..}.P....rN.I..E-........~D...2..Sa.Q...A.....E..J..KC..U....U.)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#197997)
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#13 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#15 pmsrc/src/Server(1739): pocketmine\snooze\SleeperHandler->sleepUntil(float 1709981745.4334)
#16 pmsrc/src/Server(1105): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#4, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
#18 pmsrc/src/PocketMine(364): pocketmine\server()
#19 pmsrc(11): require(string[60] phar:///home/container/pocketmine-MP.phar/src/PocketMine.php)

**Comment by supercrafter333** [comment]
Thanks. The problem is BedrockEconomy. theRankShop crashed because of a failed task by BedrockEconomy. Ist's not a direct error by theRankShop.

**Comment by TheAryqn** [comment]
> Thanks. The problem is BedrockEconomy. theRankShop crashed because of a failed task by BedrockEconomy. Ist's not a direct error by theRankShop.

Ok, thanks.

**Comment by TheAryqn** [comment]
> Thanks. The problem is BedrockEconomy. theRankShop crashed because of a failed task by BedrockEconomy. Ist's not a direct error by theRankShop.

How can I fix it?
